
import java.util.*;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author hp
 */
public class CarServiceBill extends javax.swing.JFrame {

    /**
     * Creates new form CarServiceBill
     */
    public CarServiceBill() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        EF = new javax.swing.JCheckBox();
        CF = new javax.swing.JCheckBox();
        GF = new javax.swing.JCheckBox();
        BF = new javax.swing.JCheckBox();
        jButton1 = new javax.swing.JButton();
        cb = new javax.swing.JComboBox<>();
        BS = new javax.swing.JCheckBox();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel1.setText("Car Service Bill Generator");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        jLabel2.setText("Type of Car");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel3.setText("Choose the Types of Service(s)");

        EF.setText("Engine Fixing");

        CF.setText("Clutch Fixing");

        GF.setText("Gear Fixing");

        BF.setText("Brake Fixing");

        jButton1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jButton1.setText("Generate Bill");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        cb.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        cb.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Hatchback", "Sedan", "SUV" }));

        BS.setText("Basic Servicing");

        jButton2.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jButton2.setText("Reset");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(70, 70, 70))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(GF)
                            .addComponent(BS))
                        .addGap(50, 50, 50)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(BF)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(EF)
                                .addGap(50, 50, 50)
                                .addComponent(CF)
                                .addGap(0, 50, Short.MAX_VALUE))))))
            .addGroup(layout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addContainerGap(237, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(cb, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(83, 83, 83))))
            .addGroup(layout.createSequentialGroup()
                .addGap(110, 110, 110)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(65, 65, 65)
                .addComponent(jLabel1)
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(cb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addComponent(jLabel3)
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(EF)
                    .addComponent(CF)
                    .addComponent(BS))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(GF)
                    .addComponent(BF))
                .addGap(56, 56, 56)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addContainerGap(99, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        //Identifying Type of Car
        String carType = (String) cb.getSelectedItem();
        String msg = "Type of Car - " + carType + "\nService Codes - ";
                
        int total=0;
        String msgCharges="\n", msgTotal="";
        //Creating a List  
        List<String> ServiceCode=new ArrayList<String>();  
                
        switch(cb.getSelectedIndex()){
            case 0:
                if (BS.isSelected()){
                    ServiceCode.add("BS01");
                    msgCharges = msgCharges+"Charges for Basic Charging - Rs 2000\n";
                    total = total + 2000;
                }
                if (EF.isSelected()){
                    ServiceCode.add("EF01");
                    msgCharges = msgCharges+"Charges for Engine Fixing - Rs 5000\n";
                    total = total + 5000;
                }
                if (CF.isSelected()){
                    ServiceCode.add("CF01");
                    msgCharges = msgCharges+"Charges for Clutch Fixing - Rs 2000\n";
                    total = total + 2000;
                }
                if (BF.isSelected()){
                    ServiceCode.add("BF01");
                    msgCharges = msgCharges+"Charges for Brake Fixing - Rs 1000\n";
                    total = total + 1000;
                }
                if (GF.isSelected()){
                    ServiceCode.add("GF01");
                    msgCharges = msgCharges+"Charges for Gear Fixing - Rs 3000\n";
                    total = total + 3000;
                }
                break;
            case 1:
                if (BS.isSelected()){
                    ServiceCode.add("BS01");
                    msgCharges = msgCharges+"Charges for Basic Charging - Rs 4000\n";
                    total = total + 4000;
                }
                if (EF.isSelected()){
                    ServiceCode.add("EF01");
                    msgCharges = msgCharges+"Charges for Engine Fixing - Rs 8000\n";
                    total = total + 8000;
                }
                if (CF.isSelected()){
                    ServiceCode.add("CF01");
                    msgCharges = msgCharges+"Charges for Clutch Fixing - Rs 4000\n";
                    total = total + 4000;
                }
                if (BF.isSelected()){
                    ServiceCode.add("BF01");
                    msgCharges = msgCharges+"Charges for Brake Fixing - Rs 1500\n";
                    total = total + 1500;
                }
                if (GF.isSelected()){
                    ServiceCode.add("GF01");
                    msgCharges = msgCharges+"Charges for Gear Fixing - Rs 6000\n";
                    total = total + 6000;
                }
                break;
            case 2:
                if (BS.isSelected()){
                    ServiceCode.add("BS01");
                    msgCharges = msgCharges+"Charges for Basic Charging - Rs 5000\n";
                    total = total + 5000;
                }
                if (EF.isSelected()){
                    ServiceCode.add("EF01");
                    msgCharges = msgCharges+"Charges for Engine Fixing - Rs 10000\n";
                    total = total + 10000;
                }
                if (CF.isSelected()){
                    ServiceCode.add("CF01");
                    msgCharges = msgCharges+"Charges for Clutch Fixing - Rs 6000\n";
                    total = total + 6000;
                }
                if (BF.isSelected()){
                    ServiceCode.add("BF01");
                    msgCharges = msgCharges+"Charges for Brake Fixing - Rs 2500\n";
                    total = total + 2500;
                }
                if (GF.isSelected()){
                    ServiceCode.add("GF01");
                    msgCharges = msgCharges+"Charges for Gear Fixing - Rs 8000\n";
                    total = total + 8000;
                }
                break;
            default: JOptionPane.showMessageDialog(null,"Please select the type of car");
        }
        
        for(String sc:ServiceCode)  {msg = msg+sc+", ";}
        
        msgTotal="Total Bill - Rs"+total;
                
        if (total>10000){
            msgTotal = msgTotal+"\n\nSince your Total Service Bill is more than Rs 10000, you get a COMPLIMENTARY CLEANING!!";
        }
        JOptionPane.showMessageDialog(null, msg+"\n"+msgCharges+msgTotal);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        cb.setSelectedIndex(-1);
        BS.setSelected(false);
        EF.setSelected(false);
        CF.setSelected(false);
        BF.setSelected(false);
        GF.setSelected(false);
        
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CarServiceBill.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CarServiceBill.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CarServiceBill.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CarServiceBill.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CarServiceBill().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox BF;
    private javax.swing.JCheckBox BS;
    private javax.swing.JCheckBox CF;
    private javax.swing.JCheckBox EF;
    private javax.swing.JCheckBox GF;
    private javax.swing.JComboBox<String> cb;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    // End of variables declaration//GEN-END:variables
}
